resources:

- name: the-basics-repo
  type: git
  source:
    uri: https://github.com/maliksalman/pcf-boot-samples.git
    branch: concourse

- name: pcfdev
  type: cf
  source:
    api: ((CF_API_URL))
    username: ((CF_USER))
    password: ((CF_PASSWORD))
    organization: ((CF_ORG))
    space: ((CF_SPACE))
    skip_cert_check: true

jobs:

- name: build-and-deploy
  plan:

  - get: the-basics-repo
    trigger: true

  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: maven
          tag: 3-jdk-8
      inputs:
      - name: the-basics-repo
      outputs:
      - name: the-basics-output
      run:
        path: sh
        args:
        - -exc
        - |
          mvn -f the-basics-repo/the-basics/pom.xml package
          mkdir -p the-basics-output/target
          cp the-basics-repo/the-basics/target/*.jar the-basics-output/target/
          cp the-basics-repo/the-basics/manifest.yml the-basics-output/

  - put: pcfdev
    params:
      manifest: the-basics-output/manifest.yml
