resources:

- name: the-basics-repo
  type: git
  source:
    uri: https://github.com/maliksalman/pcf-boot-samples.git
    branch: concourse

- name: pcfdev
  type: cf
  source:
    api: ((CF_API_URL))
    username: ((CF_USER))
    password: ((CF_PASSWORD))
    organization: ((CF_ORG))
    space: ((CF_SPACE))
    skip_cert_check: true

jobs:

- name: build-and-deploy
  plan:

  - get: the-basics-repo
    trigger: true

  - task: build
    file: the-basics-repo/the-basics/ci/tasks/build-and-test.yml

  - put: pcfdev
    params:
      manifest: the-basics-output/manifest.yml
