server:
  port: 9090

management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: info,health,metrics,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
        rsocket:
          enabled: false
