server:
  port: 9090
  
ribbon:
  eureka:
    enabled: false

zuul:
  routes:
      
    the-basics:
      path: /the-basics/**
      
    test-proxy:
      path: /test/*/something
      url: http://localhost:8080/
      stripPrefix: false
